name: wall3ha_app
description: ØªØ·Ø¨ÙŠÙ‚ ÙˆÙ„Ù‘Ø¹Ù‡Ø§ ðŸ”¥ â€” Ù…ÙˆÙ„Ø¯ Ø±Ø¯ÙˆØ¯ Ø°ÙƒÙŠØ© ÙˆØ·Ù‚Ø·Ù‚Ø© ÙÙŠ Ø§Ù„Ù‚Ø±ÙˆØ¨Ø§Øª

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # Ù„Ùˆ Ø­Ø§Ø¨ ØªØ¶ÙŠÙ Ø®Ø· Ø­Ù„Ùˆ Ù„Ù„ØªØ·Ø¨ÙŠÙ‚:
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700

  # Ù„Ùˆ Ø­Ø§Ø¨ ØªØ¶ÙŠÙ ØµÙˆØ± (Ù…Ø«Ù„Ø§ ØµÙˆØ± Premium â€” Ø£ÙŠÙ‚ÙˆÙ†Ø© â€” ØµÙˆØ± Ø¯Ø§Ø®Ù„ Ø§Ù„Ù‚Ø±ÙˆØ¨):
  # assets:
  #   - assets/images/
